fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    "syslog_ng": "#{source_dir}"
