language: ruby
rvm:
  - 1.8.7
  - 1.9.2
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.2.3
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.4.3

matrix:


notifications:
  email: false
gemfile: .gemfile
notifications:
  email: false
